apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghostsubs-backend
  namespace: ghostsubs
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
        role: backend

    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h pgpool-service.ghostsubs.svc.cluster.local -p 5432; do
                echo "Waiting for database..."
                sleep 2
              done
      containers:
        - name: ghostsubs-backend-container
          image: stefanvelkov/ghost-app-api:github-latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: database-config
            - secretRef:
                name: database-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
