apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: ghostsubs
data:
  POSTGRES_HOST: pgpool-service.ghostsubs.svc.cluster.local
  POSTGRES_USER: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: ghost_subs_db
  REPMGR_PORT_NUMBER: "5432"
