apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ghostsubs-database
  namespace: ghostsubs
  labels:
    app: database
spec:
  selector:
    matchLabels:
      app: database
  serviceName: database-service
  replicas: 2
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: ghostsubs-database-container
          image: bitnamilegacy/postgresql-repmgr:16
          envFrom:
            - configMapRef:
                name: database-config
            - secretRef:
                name: database-secret
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REPMGR_NODE_NAME
              value: "$(MY_POD_NAME)"
            - name: REPMGR_NODE_NETWORK_NAME
              value: "$(MY_POD_NAME).database-service"
          ports:
            - containerPort: 5432
              name: db
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: postgredb
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
